name: "Setup Environment"
description: "Setup Environment for Testing"
inputs:
  environments:
    description: 'Pixi environments'
    required: false
  docker-compose-file:
    description: 'Docker compose file'
    required: false
    default: './docker-compose.yaml'
  docker-services:
    description: 'Docker services'
    required: false

runs:
  using: composite
  steps:
    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        run-install: ${{ inputs.environments != '' }}
        environments: ${{ inputs.environments }}

    - name: Start Docker Compose
      if: ${{ inputs.docker-services != '' }}
      uses: isbang/compose-action@v2.0.0
      with:
        compose-file: ${{ inputs.docker-compose-file }}
        services: ${{ inputs.docker-services }}

    - name: Wait for Docker Servers
      if: ${{ inputs.docker-services != '' }}
      shell: bash
      run: |
        until bash ./.github/actions/setup/docker_compose_ready.sh; do
          sleep 1
        done
