name: "Setup Environment"
description: "Setup Environment for Testing"
inputs:
  python-version:
    required: true
  poetry-flags:
    description: 'Poetry flags'
    required: false
    default: ''
  docker-compose-file:
    required: false
    default: './docker-compose.yaml'
  docker-services:
    required: false

runs:
  using: composite
  steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'

    - name: Install dependencies
      shell: bash
      run: poetry install -vv ${{ inputs.poetry-flags }} --no-interaction

    - name: Start Docker Compose
      uses: isbang/compose-action@v2.0.0
      with:
        compose-file: ${{ inputs.docker-compose-file }}
        services: ${{ inputs.docker-services }}

    - name: Wait for Docker Servers
      shell: bash
      run: |
        until bash ./.github/actions/setup/docker_compose_ready.sh; do
          sleep 1
        done
