services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Pydiverse23
    ports:
      - "6543:5432"
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: PydiQuant27
    ports:
      - "1433:1433"
  zoo:
    image: zookeeper
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: ruok
      ZOO_MAX_CLIENT_CNXNS: 100
    ports:
      - "2181:2181"
  ibm_db2:
    platform: linux/x86_64
    image: icr.io/db2_community/db2
    privileged: true
    environment:
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: password
      DBNAME: testdb
      UPDATEAVAIL: NO
    ports:
      - 50000:50000
  prefect:
    image: prefecthq/prefect:3-python3.12
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console: using minioadmin:minioadmin
    command: server /tmp/minio --console-address ":9001"
