version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pipedag8
    ports:
      - 1433:1433

  zoo:
    image: zookeeper
    ports:
      - 2181:2181
