version: "3.9"
services:
  ibm_db2:
    platform: linux/x86_64
    image: icr.io/db2_community/db2
    privileged: true
    environment:
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: password
      DBNAME: testdb
      UPDATEAVAIL: NO
    ports:
      - 50000:50000
